.base:
  image: node:16
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_JOB_STAGE == "publish"'
      when: manual
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    
stages:
  - code
  - build
  - validate
  - publish

lint:
  extends: .base
  stage: code
  script:
    - yarn lint

test:
  extends: .base
  stage: code
  script:
    - yarn test

style:
  extends: .base
  stage: code
  script:
    - yarn check

build:
  extends: .base
  stage: build
  needs:
    - lint
    - test
    - style
  script:
    - yarn frigg build
  artifacts: 
    paths:
      - build/

validate:
  extends: .base
  stage: validate
  needs:
    - build
  script:
    - yarn frigg publish -t $PUBLISH_NPM_TOKEN --dry
    - yarn frigg publish-to-slack -w $PUBLISH_SLACK_WEBHOOK -c dk-hostedshop-frontend-packages -t changelog --dry

publish:
  extends: .base
  stage: publish
  needs:
    - build
    - validate
  script:
    - yarn frigg publish -t $PUBLISH_NPM_TOKEN

changelog:
  extends: .base
  stage: publish
  needs:
    - build
    - validate
  script:
    - yarn frigg publish-to-slack -w $PUBLISH_SLACK_WEBHOOK -c dk-hostedshop-frontend-packages -t changelog

storybook:
  extends: .base
  image: docker:19.03.1
  stage: publish
  tags:
    - docker
  needs:
    - build
    - validate
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - export UNIX_TIMESTAMP_NOW=$(date +%s)
    - export TAG="${CI_COMMIT_SHORT_SHA}-${UNIX_TIMESTAMP_NOW}"
    - docker build -t smartweb/freya:storybook-${TAG} .
    - docker push smartweb/freya:storybook-${TAG}
